# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 04:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(default=' ', max_length=1000, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('useful_counts', models.IntegerField(default=0)),
                ('unuseful_counts', models.IntegerField(default=0)),
                ('post_user_accept', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BBS_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='This guy is too lazy to write anything here', max_length=128)),
                ('praise', models.IntegerField(default=0)),
                ('photo', models.ImageField(default='static/cwbbs/images/woniu.jpg', upload_to='static/cwbbs/images/')),
                ('fens_counts', models.IntegerField(default=0)),
                ('experiences', models.IntegerField(default=0)),
                ('user_level', models.CharField(default='level1', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.TextField(default='\u6458\u8981(150\u5b57\u4ee5\u5185)......', max_length=300)),
                ('text', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('praise', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CWBBS.Category')),
            ],
        ),
        migrations.AddField(
            model_name='bbs_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CWBBS.Post'),
        ),
        migrations.AddField(
            model_name='bbs_comment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
