# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-22 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0003_remove_bbs_comment_father_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs_comment',
            name='father_comment_id',
            field=models.IntegerField(default=0),
        ),
    ]
