# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0004_bbs_comment_father_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_comment',
            name='comment_content',
            field=models.TextField(default='\u8bf4\u70b9\u4ec0\u4e48\u5427 ', max_length=1000, null=True),
        ),
    ]
