# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0006_auto_20160823_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs_user',
            name='nickname',
            field=models.CharField(default='', max_length=16),
        ),
    ]
