# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0007_bbs_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='nickname',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
