# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-31 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0011_post_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
