# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0012_auto_20160831_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='praise',
            name='sessionid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
