# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-13 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CWBBS', '0013_praise_sessionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Praise_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_comment_id', models.IntegerField(default=0)),
                ('is_up', models.BooleanField(default=False)),
                ('sessionid', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Praise_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_post_id', models.IntegerField(default=0)),
                ('is_up', models.BooleanField(default=False)),
                ('sessionid', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Praise_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_user_id', models.IntegerField(default=0)),
                ('is_up', models.BooleanField(default=False)),
                ('sessionid', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='praise',
            name='user',
        ),
        migrations.AlterField(
            model_name='bbs_comment',
            name='comment_content',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bbs_user',
            name='photo',
            field=models.ImageField(default='F:\\JAVA\\mysite\\src\\cwbbs/static/cwbbs/images/default.jpg', upload_to=b'F:\\JAVA\\mysite\\src\\cwbbs/static/cwbbs/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(default='150\u5b57\u6458\u8981', max_length=300),
        ),
        migrations.DeleteModel(
            name='Praise',
        ),
    ]
