# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0016_auto_20160920_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs_comment',
            name='praise',
            field=models.IntegerField(default=0),
        ),
    ]
