# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0017_bbs_comment_praise'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_statue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=0, null=True)),
                ('post_id', models.IntegerField(default=0, null=True)),
                ('is_useful', models.BooleanField(default=False)),
                ('is_accected', models.BooleanField(default=False)),
                ('sessionid', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CWBBS.BBS_user')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
