# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-22 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0018_auto_20160922_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_statue',
            name='sessionid',
        ),
    ]
