# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-23 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWBBS', '0019_remove_comment_statue_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_statue',
            name='is_accected',
        ),
        migrations.AlterField(
            model_name='comment_statue',
            name='is_useful',
            field=models.IntegerField(default=0),
        ),
    ]
